### PR TITLE
Py3 compatibility for occweb

### PR DESCRIPTION
**Pull request by taldcroft**
Was kadi ever passing occweb tests on Py3?  I'm confused because I thought ska_testr was OK on Ska3, but that isn't what I'm now seeing.

Anyway I noticed these test failures and so fixed the code to pass on Py3.

Closes #101

### CODE REVIEW

**Comment by jeanconn** [comment]
I thought the occweb fixes were already in #101 

That's what I've been testing against, figuring we'd install at some point.

**Comment by taldcroft** [comment]
Grrr, I guess I should have checked open PRs.  Anyway, I'll make some combination of the two PRs and merge.

I don't quite understand your ska_testr process.  Are you using a custom version that checks out this branch?

**Comment by jeanconn** [comment]
No.  I was just adding my kadi repo to my PYTHONPATH until this got installed.

**Comment by jeanconn** [comment]
Merged or not, I'm in a holding pattern on the Ska3 environment.  There's a risk of getting out of sync if Ska3 package updates go into skare before you decide if the environment gets promoted.

**Comment by jeanconn** [comment]
I also think the kadi tests just seem to hang on unagi Py3, but that wasn't a regression in my new Py3 environment and I hadn't figured out what it was trying to do before the hang.

**Comment by taldcroft** [comment]
This is passing tests on unagi on ska and ska3.  In both cases the tests run quite slowly and appear to hang, but with patience will finish in a couple of minutes.

**Comment by taldcroft** [comment]
Skare master and py3 branches have been updated (master: direct commit, py3: cherry-pick).

This is installed on HEAD ska test, HEAD ska flight, HEAD ska3 flight.  Unit tests on all three on unagi pass.

**Comment by jeanconn** [comment]
When you say " will finish in a couple of minutes" are those the ska_testr regression tests or the kadi module tests?

**Comment by taldcroft** [comment]
Kadi module tests.

**Pull request merged**
