### PR TITLE
Add `type` field to Dump event class and update docs and process notes

### PR DESCRIPTION
**Pull request by taldcroft**
## Description

The primary driver for this PR is to add a `type` field to the momentum `Dump` event which indicates if this dump was ground commanded or autonomous.

In doing this I noted that the process notes files were out of date and substantively wrong in many places, so I took the opportunity to do some re-organization and clean-up.

## Interface impacts

Adds a `type` field to `dumps`, but is otherwise back compatible. In particular the new database works with old code.

### Unit tests

- [x] Mac

Independent check of unit tests by Jean (with this PR's events3.db3)
- [x] Linux

### Functional tests

The update process now described in `NOTES.events_maintain.rst` was followed end-to-end. This includes functional testing:

- Database file includes the updated `Dump` events with the `type` field. 
- Using the new database file with the current flight release of kadi still passes tests and allows reading `dumps`.

The new `events3.db3` file is available on HEAD in `/proj/sot/ska/data/kadi/rc`.

### CODE REVIEW

**Comment by jeanconn** [comment]
Does this line do anything at this point?

https://github.com/sot/kadi/pull/264/files#diff-d63b68babdc09c7533bc1a95fb271638f0234e0726d02c3a5781b0783c02609fR1164

**Review by jeanconn — COMMENTED** [review]
Other than wondering about event_val = 'GRND' this looks good to me.

**Comment by taldcroft** [comment]
I'm pretty sure `event_val = 'GRND'` is not doing anything, but I don't want to re-test.

**Review by jeanconn — APPROVED** [review]
OK, if the defunct event_val = 'GRND' is benign, I don't have other issues with this.  Make sense.

**Pull request merged**
