### PR TITLE
Kadi web enhancements

### PR DESCRIPTION
**Pull request by jeanconn**
The 'web' branch with a collection of kadi web server enhancements.

### CODE REVIEW

**Comment by jeanconn** [comment]
A PR with the idea of just merging `web` as I don't know why it is persisting as an independently-developed branch.

**Comment by taldcroft** [comment]
I think this made sense when web-kadi was less stable, but I agree it's time to merge this branch back and henceforth use the flight release for the web server.

**Comment by jeanconn** [comment]
I see no conflicts in these changes, so I think this is good to go.

**Comment by taldcroft** [comment]
:+1:

**Pull request merged**
