### PR TITLE
Update tests for last bugfix

### PR DESCRIPTION
**Pull request by jeanconn**
Update tests in kadi.commands for the WSVIDALLDN ccd_count change.

### CODE REVIEW

**Comment by jeanconn** [comment]
Not time critical.. I just needed a break and this was bugging me.

**Comment by jeanconn** [comment]
flight ska
```
ska-fido: py.test
============================= test session starts ==============================
platform linux2 -- Python 2.7.9 -- py-1.4.26 -- pytest-2.6.4
collected 49 items 

kadi/cmds/tests/test_commands.py ..
kadi/commands/tests/test_commands.py ...
kadi/commands/tests/test_states.py .....s.............x..........
kadi/tests/test_events.py ..........
kadi/tests/test_occweb.py ....

============== 47 passed, 1 skipped, 1 xfailed in 111.74 seconds
```
ska3/flight
```
ska3-fido: py.test
============================= test session starts ==============================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /proj/sot/ska/jeanproj/git/kadi, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 49 items                                                              

kadi/cmds/tests/test_commands.py ..
kadi/commands/tests/test_commands.py ...
kadi/commands/tests/test_states.py .....s.............x..........
kadi/tests/test_events.py ..........
kadi/tests/test_occweb.py ....

============== 47 passed, 1 skipped, 1 xfailed in 111.27 seconds
```
ska3/matlab32
```
quango: py.test
============================= test session starts ==============================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /proj/sot/ska/jeanproj/git/kadi, inifile:
plugins: arraydiff-0.2, doctestplus-0.1.3, openfiles-0.3.0, remotedata-0.3.0
collected 49 items                                                              

kadi/cmds/tests/test_commands.py ..
kadi/commands/tests/test_commands.py ...
kadi/commands/tests/test_states.py .....s.............x..........
kadi/tests/test_events.py ..........
kadi/tests/test_occweb.py ....

============== 47 passed, 1 skipped, 1 xfailed in 201.43 seconds 
```

**Comment by jeanconn** [comment]
Does this test change need LR approval or good-to-go whenever?

**Comment by taldcroft** [comment]
Good to go whenever based on only version and test module updates.

**Pull request merged**
