### PR TITLE
Add mica star history app

### PR DESCRIPTION
**Pull request by jeanconn**
Add mica star history app

### CODE REVIEW

**Comment by taldcroft** [comment]
Looks good, at least on paper.

**Comment by jeanconn** [comment]
OK.  Next stages with the "looks good on paper" approval?  Given nothing calls it, can the app just go?

**Comment by taldcroft** [comment]
This needs coordinated testing / review with https://github.com/sot/mica/pull/79.  I'll have a look.

**Comment by taldcroft** [comment]
When the page is loaded initially there is a message `No acq or guide history for star ::`.  That should be suppressed.

**Comment by taldcroft** [comment]
I think an actual `Submit` button would be helpful.  Just hitting return is not 100% intuitive.

**Comment by taldcroft** [comment]
The `obsid` value should be a link to the corresponding mica page.

**Comment by taldcroft** [comment]
`star tracked` needs an explanation.  At this point the `Notes:` should be a bulleted list.

**Comment by taldcroft** [comment]
Is the plan to retire https://icxc.harvard.edu/cgi-bin/aspect/get_stats/get_stats.cgi ?

**Comment by jeanconn** [comment]
Regarding 'Submit', for some reason I thought you didn't like them in the kadi pages (maybe using the mica page as a reference?).  I prefer having them myself and that's not a problem.  Thanks for the feedback!

**Comment by jeanconn** [comment]
And yes, my plan was to begin to plug in this page to replace get_stats.cgi.

**Comment by taldcroft** [comment]
About Submit, I guess I find that if there is just one input box it seems to be clear to hit enter, but with more than one it isn't so much.  My taste can evolve on the time scale of open PRs, but it's not a huge deal.

**Comment by taldcroft** [comment]
`start time` and `stop time` should be capitalized.

**Comment by taldcroft** [comment]
Slightly out of scope, but what about including a table of the corresponding AGASC entry for the star?  This might be relevant/useful in some cases.

**Comment by taldcroft** [comment]
OK, I've finished my review, looks good!

**Comment by jeanconn** [comment]
Regard the table of the AGASC entry, that does make sense.  I suppose I was also thinking about using this tool to replace the "static" pages we have in mica with the star history content:

https://icxc.cfa.harvard.edu/aspect/mica_reports/18/18625/star_397676392.html

and those pages already have the AGASC info, so I should have just brought that over to this display anyway.

**Comment by taldcroft** [comment]
> I suppose I was also thinking about using this tool to replace the "static" pages we have in mica with the star history content

Yes!  And good to see you already have some code and a template to make this table in a nice view.

**Pull request merged**
